<a href="https://colab.research.google.com/github/Liang130520/tibaml1017/blob/main/class1017-machine_learning-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 統計需要的資料量
# Machine learning: 1K 以上, Deep learning: 1W以上
# 資料量多寡 -> 問題難度(大概跟欄位數目掛勾)

import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
# iris # 鳶尾花的所有資料
df = pd.DataFrame(iris["data"], columns = iris["feature_names"]) # pandas的表個型態
df["ans"] = iris["target"]
df

load_iris 詳細資料-> feature_names': ['sepal length (cm)',  'sepal width (cm)',  'petal length (cm)',  'petal width (cm)'], 'filename': 'iris.csv', 'data_module': 'sklearn.datasets.data'}
'target_names': array(['setosa', 'versicolor', 'virginica'] 分別對應 target 0, 1, 2


In [37]:
# 處理資料: pandas -> DataFrame
# 進到sklearn: numpy -> array
import numpy as np
from sklearn.model_selection import train_test_split

x = df.drop("ans", axis = 1) # 去除直欄
x = np.array(x)
y = np.array(df["ans"])
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1) # 90% x, 10% x, 90% y, 10% y
show = x_test
print(show)
print("-----------------------")
x_train
# train_test_split([1, 2, 3, 4],
#                   [5, 6, 7, 8],
#                   [9, 10, 11, 12],
#                   test_size = 0.25)  
# # test_size 進行 ?:? 內容隨機切等分, ex:0.25 = 1:3, 0.1 = 1:9, 且若有多選項, 將會有同相對應位置

[[6.4 2.8 5.6 2.2]
 [5.7 3.  4.2 1.2]
 [6.4 3.1 5.5 1.8]
 [6.  2.7 5.1 1.6]
 [5.1 2.5 3.  1.1]
 [5.8 2.7 5.1 1.9]
 [6.3 2.7 4.9 1.8]
 [6.3 2.5 5.  1.9]
 [5.1 3.8 1.6 0.2]
 [5.5 2.4 3.7 1. ]
 [5.  3.3 1.4 0.2]
 [5.4 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [4.8 3.4 1.6 0.2]]
-----------------------


array([[4.4, 3.2, 1.3, 0.2],
       [5.6, 2.7, 4.2, 1.3],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 2.3, 4.4, 1.3],
       [5. , 3.2, 1.2, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [5.6, 3. , 4.5, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 4. , 1. ],
       [5.6, 3. , 4.1, 1.3],
       [4.7, 3.2, 1.3, 0.2],
       [5.6, 2.9, 3.6, 1.3],
       [6.8, 3. , 5.5, 2.1],
       [6. , 2.9, 4.5, 1.5],
       [7.7, 2.8, 6.7, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [5.2, 2.7, 3.9, 1.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [6.5, 3. , 5.5, 1.8],
       [5.1, 3.4, 1.5, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [4.5, 2.3, 1.3, 0.3],
       [7.2, 3.2, 6. , 1.8],
       [6.8, 2.8, 4.8, 1.4],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4. , 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5.1, 3

In [31]:
d = pd.DataFrame([
        [1, 2],
        [3, 4]
    ], columns = ["a", "b"], index = ["a", "b"])

d.drop("a", axis = 0) # b(3, 4) 列 a 被刪去
d.drop("a", axis = 1) # b(2, 4) 欄 a 被刪去

b
a  2
b  4